index:
    path: /
    controller: App\Controller\CleanController::index
about:
    path: /about
    controller: App\Controller\CleanController::about
contact:
    path: /contact
    controller: App\Controller\CleanController::contact

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
